Fix typo when creating an INDEX
If INDEX is not UNIQUE, query fail due to missing space.

```
ERROR:  syntax error at or near "CREATEINDEX" at character 1
```